package dev.vaibhav.musicx.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF0061a7)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd1e4ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001c38)
val md_theme_light_secondary = Color(0xFF535f70)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd7e3f8)
val md_theme_light_onSecondaryContainer = Color(0xFF101c2b)
val md_theme_light_tertiary = Color(0xFF6c5778)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf4d9ff)
val md_theme_light_onTertiaryContainer = Color(0xFF251430)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfcff)
val md_theme_light_onBackground = Color(0xFF1b1b1b)
val md_theme_light_surface = Color(0xFFfdfcff)
val md_theme_light_onSurface = Color(0xFF1b1b1b)
val md_theme_light_surfaceVariant = Color(0xFFdfe2eb)
val md_theme_light_onSurfaceVariant = Color(0xFF43474e)
val md_theme_light_outline = Color(0xFF73777f)
val md_theme_light_inverseOnSurface = Color(0xFFf1f0f3)
val md_theme_light_inverseSurface = Color(0xFF2f3033)
val md_theme_light_inversePrimary = Color(0xFF9fcaff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF9fcaff)
val md_theme_dark_onPrimary = Color(0xFF00325b)
val md_theme_dark_primaryContainer = Color(0xFF004880)
val md_theme_dark_onPrimaryContainer = Color(0xFFd1e4ff)
val md_theme_dark_secondary = Color(0xFFbbc7db)
val md_theme_dark_onSecondary = Color(0xFF253141)
val md_theme_dark_secondaryContainer = Color(0xFF3c4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFd7e3f8)
val md_theme_dark_tertiary = Color(0xFFd8bee4)
val md_theme_dark_onTertiary = Color(0xFF3c2948)
val md_theme_dark_tertiaryContainer = Color(0xFF533f5f)
val md_theme_dark_onTertiaryContainer = Color(0xFFf4d9ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1b1b1b)
val md_theme_dark_onBackground = Color(0xFFe2e2e6)
val md_theme_dark_surface = Color(0xFF1b1b1b)
val md_theme_dark_onSurface = Color(0xFFe2e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF43474e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc3c6cf)
val md_theme_dark_outline = Color(0xFF8d9199)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1b)
val md_theme_dark_inverseSurface = Color(0xFFe2e2e6)
val md_theme_dark_inversePrimary = Color(0xFF0061a7)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF0061a7)
val error = Color(0xFFba1b1b)
